---
title: Research
toc: true
---

## Working papers

"The China shock and internal migration: Evidence from bilateral migration flows" with [Jaerim Choi](https://sites.google.com/view/jaerimchoi) and [Seung Hoon Lee](https://sites.google.com/view/seunghoon/home) \[[Working Paper\]](https://www.dropbox.com/scl/fi/biigga26hxs7jcfu8bwtp/migration_china_shock.pdf?rlkey=1ycpxjq450jet62a8vdrew19m&e=1&dl=0).

<details>
  <summary>Abstract</summary>
  Using Korean administrative datasets spanning almost two decades and covering nearly the entire bilateral internal migration flows between local labor markets, we identify the causal impact of the China trade shock on internal migration. The trade shock affects in-migration, but not out-migration. Separating further the China trade shock into export and import shocks, we find that export expansion increases in-migration, whereas import competition reduces in-migration. By decomposing the impact of trade shock into age groups, we find that effects of trade shocks in destination are robust and statistically significant across age groups; and most pronounced for middle-aged people between the ages of 45 and 64. Finally, households with male heads are more likely to be influenced by the trade shock compared to those with female heads, due to the greater reliance of the manufacturing sector on male labor.
</details>

## Publications

[2] "Does political conflict hurt immigration? Evidence from the South Korea -- China THAAD Dispute" with [Jongkwan Lee](https://sites.google.com/site/kwanlee84/home?authuser=0). Published in **_Southern Economic Journal_** \[[Paper](https://onlinelibrary.wiley.com/doi/10.1002/soej.12723)\].

[1] "The well-being of cities: Estimating migration attractiveness from internal migration across Korean cities" with [Seung Hoon Lee](https://sites.google.com/view/seunghoon/home) and Ji Sub Park. Published in **_Global Economic Review_** \[ [Paper](https://www.tandfonline.com/doi/full/10.1080/1226508X.2023.2282622?scroll=top&needAccess=true) \]

